### PR TITLE
Updates README network section with better example

### PR DESCRIPTION
**Pull request by jmgilman**
Addresses #40 by making a small addendum in the network section example to show how to use the network name when creating a container.

### CODE REVIEW

**Comment by jmgilman** [comment]
I took a crack at fixing the CI errors. Notably, I bumped the minimum Python version to 3.7.0 since 3.6 [went EOL](https://endoflife.date/python) this year anyways.

**Comment by Jc2k** [comment]
Thanks so much! Wasn't sure when I was gonna find the time for that 🤣 good call on 3.6.

**Comment by Jc2k** [comment]
I think we want to have pytest run in the root dir so that pytest-markdown runs for the README. Or maybe specifically pass the readme to pytest.

**Comment by jmgilman** [comment]
Ah, that makes more sense. I couldn't figure out why it was hitting the README, didn't realize there was a plugin that was grabbing it.

**Comment by Jc2k** [comment]
I'm really bad at testing my documentation so I thought i better run it as tests 😆

**Comment by jmgilman** [comment]
Well turns out I'm just as bad since I didn't modify the imports on the example I expanded upon :) I think everything should pass now and I reverted `pytest` to start from the root again.

**Comment by Jc2k** [comment]
Awesome! Thank you so much for sorting that out 😄

**Comment by Jc2k** [comment]
I have done a release that unpins the docker version (3.1.3). But I don't think that will stop your alert, unfortunately:

https://github.com/docker/docker-py/pull/2943

**Comment by Jc2k** [comment]
Kinda looks like the official python docker client is unmaintained

**Pull request merged**
