### PR TITLE
Add pytester tests for reusable containers

### PR DESCRIPTION
**Pull request by Jc2k**
This branch adds `pytester` tests for the new reusable containers feature.

### CODE REVIEW

**Comment by Jc2k** [comment]
@alexanderpetrenz what do you think to this as a starting point?

**Comment by Jc2k** [comment]
Applied the same test to `networks` and it breaks - I think valid bugs remain with reusable containers for volumes and networks.

**Comment by Jc2k** [comment]
Sooo the docker API is inconsistent.

It was letting us create multiple networks with the same name This meant we never actually "reused" a network on purpose (if you had inspected the network fixture in a test it's id would have changed every run). So it leaked networks. I ended up with many duplicates.

Volume creation seems to be idempotent. If you do `docker volume create test` multiple times they all "work" but only one `work` volume exists. So the problem didn't manifest there in the same way. If you named your volumes they were in effect reused. But unamed resources for both are given a random name by pytest-docker-tools. So volumes are leaked too.

I have fixed both of these by duplicating @alexanderpetrenz's logic from container creation to networks and volumes as well.

In addition I have improved label handling for all 3. Previously the reusable containers labels would have clobbered labels set by the developer using pytest-docker-tools. The new approach merges their labels and ours. This still needs a test.

**Review by alexanderpetrenz — APPROVED** [review]
Well so in the end my changes to networks and volumes were quite sloppy. Pretty concerning, sorry about that!
It's great to see that there are now tests on this! I also like the clean up on the factories as their code is now pretty clear again.

I made some adjustments to the README, to cover the changes to networks and volumes. I'll make a PR for that.

**Comment by Jc2k** [comment]
Thanks for the review. No problem, I missed the problems in review too! Need to add more  of these pytester tests...

**Comment by Jc2k** [comment]
@alexanderpetrenz just wanted to warn you that i'd renamed one of the labels to be consistent everywhere now that they aren't just for containers. So `container-creator` is just `creator`.

I'm thinking of changing `pytest-docker-tools.reusable-container` to `pytest-docker-tools.reusable` too.

Because these are technically breaking changes i'll bump to 2.0.x (and try to be more strict about version numbers going forwards - i should have done a minor bump for the new feature 😢 

It might be tuesday before i get time to do a release, so please let me know if you have any concerns about any of this.

**Pull request merged**
